import { defineAsyncComponent } from 'vue'
import ToolLoadError from '@/components/ToolLoadError.vue'

// 异步加载失败时展示可重试的错误组件,避免弱网下白屏
export function lazy(loader) {
  return defineAsyncComponent({
    loader,
    errorComponent: ToolLoadError,
    delay: 120,
  })
}

export const CATEGORIES = [
  { id: 'convert', name: '编码转换', icon: 'repeat' },
  { id: 'dev', name: '开发工具', icon: 'wrench' },
  { id: 'text', name: '文本工具', icon: 'file-text' },
  { id: 'image', name: '图片工具', icon: 'image' },
  { id: 'generate', name: '生成器', icon: 'sparkles' },
  { id: 'calc', name: '计算换算', icon: 'calculator' },
  { id: 'doc', name: '文档处理', icon: 'files' },
  { id: 'dconv', name: '文档转换', icon: 'arrow-left-right' },
  { id: 'av', name: '音视频', icon: 'clapperboard' },
  { id: 'chart', name: '数据图表', icon: 'chart-column' },
  { id: 'office', name: '办公辅助', icon: 'paperclip' },
  { id: 'software', name: '软件推荐', icon: 'hard-drive' },
]

export const TOOLS = [
  // ---------- 编码转换 ----------
  {
    id: 'json', name: 'JSON 格式化', category: 'convert', icon: 'braces',
    desc: '格式化、压缩、校验 JSON 数据,精准提示语法错误',
    keywords: 'json 格式化 压缩 校验 format prettify',
    about: '粘贴 JSON 后点击「格式化」可美化缩进,「压缩」移除所有空白。输入框右侧实时显示 JSON 是否合法;语法错误信息由浏览器解析器给出,可定位到行。',
    component: lazy(() => import('./json/JsonFormatter.vue')),
  },
  {
    id: 'base64', name: 'Base64 编解码', category: 'convert', icon: 'type',
    desc: '文本与 Base64 互相转换,支持 URL 安全模式',
    keywords: 'base64 encode decode 编码 解码',
    about: '按 UTF-8 字节序列编码,中文不会乱码。URL 安全模式用 - _ 替代 + / 并去掉填充符,适合放在 URL 或文件名中。',
    component: lazy(() => import('./base64/Base64Tool.vue')),
  },
  {
    id: 'base-enc', name: 'Base 编码', category: 'convert', icon: 'boxes',
    desc: 'Base32 / Base58 / Base62 与文本互转,中文按 UTF-8 处理',
    keywords: 'base32 base58 base62 编码 解码 bitcoin cid 短链 totp',
    about: '三种常用 Base 编码:Base32(RFC 4648,TOTP 密钥与配置常用)、Base58(Bitcoin 字母表,地址与 IPFS CID)、Base62(短链与邀请码)。全部按 UTF-8 字节、BigInt 实现,中文不乱码;解码容忍小写与缺失填充,非法字符给出明确报错,支持编码/解码一键反向继续。',
    component: lazy(() => import('./base-enc/BaseEncTool.vue')),
  },
  {
    id: 'url', name: 'URL 编解码', category: 'convert', icon: 'link',
    desc: 'URL 百分号编码与解码,支持表单空格转 +',
    keywords: 'url encode decode uri 百分号编码',
    about: '对应 JavaScript 的 encodeURIComponent / decodeURIComponent。表单风格空格转 + 常见于 GET 查询参数的 application/x-www-form-urlencoded 编码。',
    component: lazy(() => import('./url/UrlEncoder.vue')),
  },
  {
    id: 'html-entity', name: 'HTML 转义', category: 'convert', icon: 'shield',
    desc: 'HTML 特殊字符转义与反转义,防止代码被误解析',
    keywords: 'html escape 转义 实体 特殊字符',
    about: '把 < > & " \' 转成 HTML 实体,在页面中安全展示代码片段;反转义支持命名实体与数字实体。',
    component: lazy(() => import('./html-entity/HtmlEscape.vue')),
  },
  {
    id: 'html-to-md', name: 'HTML → Markdown', category: 'text', icon: 'file-output',
    desc: '网页 HTML 片段转 Markdown,复制笔记即用',
    keywords: 'html markdown 转换 网页 笔记 复制 turndown',
    about: '把 HTML 片段转成 Markdown:标题/加粗斜体/链接图片/列表/围栏代码块等常见标签均可识别,可直接打开本地 .html 文件。与「Markdown 预览」互为反向。工具参数会同步到地址栏,点标题栏「分享状态」或直接复制链接即可分享当前配置。',
    component: lazy(() => import('./html-to-md/HtmlToMd.vue')),
  },
  {
    id: 'radix', name: '进制转换', category: 'convert', icon: 'binary',
    desc: '二进制、八进制、十进制、十六进制数字互转,支持大数',
    keywords: '进制 二进制 十六进制 binary hex radix 大数',
    about: '基于 BigInt 实现,可处理超过 2^53 的任意大整数;支持 0x / 0b / 0o 前缀输入。工具参数会同步到地址栏,点标题栏「分享状态」或直接复制链接即可分享当前配置。',
    component: lazy(() => import('./radix/RadixConverter.vue')),
  },
  {
    id: 'text-radix', name: '文本进制互转', category: 'convert', icon: 'text-cursor-input',
    desc: '文本与二进制/八进制/十进制/十六进制(ASCII)互转',
    keywords: '文本 二进制 十六进制 ascii 十进制 八进制 文本转十六进制',
    about: '按 UTF-8 字节逐个转换,中文会被编码为 3 个字节。解密模式支持带空格与紧凑两种格式。',
    component: lazy(() => import('./text-radix/TextRadix.vue')),
  },
  {
    id: 'unicode-escape', name: 'Unicode 转义', category: 'convert', icon: 'globe',
    desc: '文本与 \\uXXXX Unicode 转义序列互转',
    keywords: 'unicode 转义 \\u 编码 解码 中文',
    about: '常用于查看配置文件里的中文转义(如 properties 文件)。emoji 等增补平面字符会正确拆为代理对。',
    component: lazy(() => import('./unicode-escape/UnicodeEscape.vue')),
  },
  {
    id: 'hash', name: '哈希计算', category: 'convert', icon: 'hash',
    desc: '计算文本的 SHA-1 / SHA-256 / SHA-384 / SHA-512 摘要',
    keywords: 'hash sha256 sha1 sha512 摘要 校验 哈希',
    about: '由浏览器 Web Crypto API 在本地计算。哈希是单向摘要,无法反推原文;需要校验文件请用「开发工具 → 文件哈希」。',
    component: lazy(() => import('./hash/HashTool.vue')),
  },
  {
    id: 'md5', name: 'MD5 编码', category: 'convert', icon: 'lock',
    desc: '计算文本的 MD5 摘要,支持 32 位 / 16 位、大小写',
    keywords: 'md5 编码 摘要 哈希 校验',
    about: 'MD5 已不具备密码学安全性,仅建议用于普通数据校验或历史系统兼容;安全场景请用 SHA-256。',
    component: lazy(() => import('./md5/Md5Tool.vue')),
  },
  {
    id: 'url-parser', name: 'URL 解析', category: 'convert', icon: 'puzzle',
    desc: '拆解 URL 的协议、域名、路径与查询参数表',
    keywords: 'url 解析 参数 query 解析域名 网址',
    about: '自动解码查询参数的百分号编码,每个参数可单独复制;端口显示默认值并可在复制时自动去除注释。',
    component: lazy(() => import('./url-parser/UrlParser.vue')),
  },
  {
    id: 'xml-format', name: 'XML 格式化', category: 'convert', icon: 'code-xml',
    desc: '格式化、压缩、校验 XML,支持 CDATA 与注释',
    keywords: 'xml 格式化 压缩 校验 美化 format soap rss',
    about: '基于浏览器原生 XML 解析器,输入非法 XML 会给出报错定位。格式化时只含文本的元素保持单行,CDATA 与注释原样保留;压缩会去除标签之间的缩进空白,但元素内文本原样不动。',
    component: lazy(() => import('./xml-format/XmlFormat.vue')),
  },
  {
    id: 'xml2json', name: 'XML ↔ JSON', category: 'convert', icon: 'repeat-2',
    desc: 'XML 与 JSON 双向转换,属性、数组、文本按约定映射',
    keywords: 'xml json 转换 互转 属性 数组 解析 配置 rss',
    about: '元素属性转成「@属性名」键、元素内文本转成「#text」键,只有文本的元素直接输出字符串,同名兄弟元素合并为数组;反向转换时顶层必须是单键对象。支持双向结果互换后继续编辑,非法输入会给出可读的报错。',
    component: lazy(() => import('./xml2json/Xml2Json.vue')),
  },
  {
    id: 'json-tree', name: 'JSON 树查看器', category: 'convert', icon: 'list-tree',
    desc: '把 JSON 解析成可折叠的结构树,层级一目了然',
    keywords: 'json 树 结构 层级 可视化 viewer 折叠 查看器',
    about: '与「JSON 格式化」互补:那边看文本,这边看结构。支持节点折叠/展开、类型徽章(字符串/数字/布尔/null/对象/数组)、悬停复制节点路径(如 $.tools[0].id),关键字过滤(匹配键名或值,命中高亮并自动展开其路径,只显示命中节点与其上级),并统计节点总数与最大深度;超过 1500 个节点时自动折叠深层以保持流畅。',
    component: lazy(() => import('./json-tree/JsonTree.vue')),
  },
  {
    id: 'json-to-ts', name: 'JSON → TypeScript', category: 'dev', icon: 'brackets',
    desc: '从 JSON 样本推断 TypeScript 接口定义',
    keywords: 'json typescript ts 接口 类型 生成 interface 联调',
    about: '粘贴一段 JSON 样本(接口返回、配置文件),自动生成对应的 interface/type:嵌套对象逐层生成、数组取元素形状并集、同形对象按结构签名去重只生成一次、非法标识符键自动加引号。根类型名可自定义。工具参数会同步到地址栏,点标题栏「分享状态」或直接复制链接即可分享当前配置。',
    component: lazy(() => import('./json-to-ts/JsonToTs.vue')),
  },
  {
    id: 'float-bits', name: '浮点数解剖', category: 'dev', icon: 'sigma',
    desc: '看数字在 IEEE 754 双精度/单精度下的实际存储位型',
    keywords: '浮点数 ieee754 精度 位型 二进制 尾数 指数 float double 0.1',
    about: '输入任意数字,展示它在 64 位 double(JS 的 number)与 32 位 float 下的符号/指数/尾数位与十六进制位型,附特殊值分类(零/次正规数/无穷大/NaN)与 32 位舍入回读对比,理解 0.1+0.2 !== 0.3 的直观入口。位型由 DataView 写入后按字节读出,与平台无关。数值会同步到地址栏,点标题栏「分享状态」或直接复制链接即可分享当前配置。',
    component: lazy(() => import('./float-bits/FloatBitsView.vue')),
  },
  {
    id: 'docker-compose', name: 'Docker run → compose', category: 'dev', icon: 'container',
    desc: '把 docker run 命令转成 docker-compose.yml',
    keywords: 'docker run compose 容器 yaml 转换 部署',
    about: '解析 docker run 的常用旗标(-d/-it/-p/-v/-e/--name/--restart/--network/--privileged 与镜像后的启动命令)生成 compose 服务块;未识别的旗标不会被静默丢弃,而是列在下方提醒手动补全。引号内空格会被正确处理。工具参数会同步到地址栏,点标题栏「分享状态」或直接复制链接即可分享当前配置。',
    component: lazy(() => import('./docker-compose/DockerCompose.vue')),
  },
  {
    id: 'curl-to-fetch', name: 'curl → 代码', category: 'dev', icon: 'terminal',
    desc: '把 curl 命令转成 JavaScript fetch 或 Python requests 代码',
    keywords: 'curl fetch requests 转换 http 请求 接口 调试 转代码 javascript python',
    about: '粘贴 curl 命令(支持多行续行与引号转义),生成可直接使用的 JavaScript fetch 或 Python requests 代码:解析 -X 方法、-H 请求头、-d 请求体(多个用 & 连接、JSON 体自动补 Content-Type)、-F 表单(含 @文件,生成 FormData/files 代码)、-u 基本认证与 --get。未识别的旗标会列出提醒,不被静默丢弃。与「Docker run → compose」同一套解析策略。命令里常带密钥,本工具不写入地址栏也不发任何请求。',
    component: lazy(() => import('./curl-to-fetch/CurlToFetch.vue')),
  },
  {
    id: 'id-card-parse', name: '身份证号解析', category: 'dev', icon: 'square-user',
    desc: '解析省份 / 生日 / 性别 / 年龄,校验 GB 11643 校验位',
    keywords: '身份证 解析 校验 校验位 身份证号 验证 测试数据 隐私 打码',
    about: '解析 18 位身份证号的省级行政区(前 2 位)、出生日期、性别(第 17 位奇偶)与周岁,并按 GB 11643-1999 加权取模校验末位校验码;附一键打码展示(保留前 6 后 4)。校验位正确不代表号码真实存在,仅供开发测试验证格式,可配合「随机测试数据」使用。号码是敏感信息,本工具不写入地址栏、不联网。',
    component: lazy(() => import('./id-card-parse/IdCardParse.vue')),
  },
  {
    id: 'sql-params', name: 'SQL 参数填充', category: 'dev', icon: 'table-2',
    desc: '把 ? / $n 占位符与绑定参数还原成可执行的 SQL',
    keywords: 'sql 参数 占位符 填充 慢查询 日志 预编译 绑定变量 调试',
    about: '慢查询日志 / ORM 只给你参数化 SQL 和一串绑定参数?粘贴两段自动拼成可直接执行的语句:支持 ? 与 $n 两种占位符,字符串自动转义引号(MySQL 反斜杠风格可选),JSON 里的 null / true / false / 数字输出对应字面量,SQL 字符串字面量与行注释里的 ? 不会误判,参数个数不匹配时明确报错。带密钥的语句不写入地址栏。',
    component: lazy(() => import('./sql-params/SqlParams.vue')),
  },
  {
    id: 'totp', name: 'TOTP 两步验证码', category: 'dev', icon: 'timer-reset',
    desc: '本地生成 2FA 动态验证码,不用掏手机',
    keywords: 'totp 2fa 两步验证 动态验证码 otp 身份验证器 google authenticator',
    about: '粘贴 2FA 设置页给出的 Base32 密钥(或生成随机密钥用于测试),本地实时计算动态验证码,支持 6/8 位、30/60 秒与 SHA-1/256/512。已通过 RFC 6238 全套官方向量验证。⚠️ 密钥仅在本页内存中参与计算,不写入任何存储;本工具不能替代官方验证器管理你的真实账号,请自行权衡。工具参数会同步到地址栏,点标题栏「分享状态」或直接复制链接即可分享当前配置。',
    component: lazy(() => import('./totp/TotpTool.vue')),
  },
  {
    id: 'jwt', name: 'JWT 解析与签名', category: 'convert', icon: 'ticket',
    desc: '解码 JWT 的 Header / Payload,支持 HS256 签名生成与校验',
    keywords: 'jwt token 解码 解析 鉴权 过期 签名 hs256 生成 校验',
    about: '「解析」页解码 Header / Payload 并根据 exp 提示是否过期;「签名 / 校验」页用 WebCrypto 在本地完成 HS256/384/512 签名生成与验证(重算签名比对,可确认 Token 是否由该密钥签发、是否被篡改)。RS/ES 等非对称算法涉及私钥管理,不适合在网页操作;切勿粘贴生产环境密钥。',
    component: lazy(() => import('./jwt/JwtTool.vue')),
  },
  {
    id: 'sm-crypto', name: '国密 SM2/SM3/SM4', category: 'convert', icon: 'shield-check',
    desc: '国密算法:SM3 摘要、SM4 加解密、SM2 公私钥加解密',
    keywords: '国密 sm2 sm3 sm4 加密 解密 哈希 签名',
    about: 'SM3 输出 256 位摘要;SM4 支持 ECB/CBC;SM2 为 C1C3C2 模式,可一键生成密钥对。全部由 sm-crypto 在本地完成。',
    component: lazy(() => import('./sm-crypto/SmCryptoTool.vue')),
  },

  // ---------- 开发工具 ----------
  {
    id: 'sql-format', name: 'SQL 格式化', category: 'dev', icon: 'database',
    desc: '美化杂乱的 SQL,支持 MySQL / PostgreSQL 等 10 种方言',
    keywords: 'sql 格式化 美化 缩进 mysql postgresql 数据库',
    about: '基于 sql-formatter,支持主流数据库方言与关键字大小写控制;语句有语法错误时会提示而不会输出错误结果。',
    component: lazy(() => import('./sql-format/SqlFormat.vue')),
  },
  {
    id: 'yaml-json', name: 'YAML ↔ JSON', category: 'dev', icon: 'settings',
    desc: 'YAML 与 JSON 双向转换,支持多文档',
    keywords: 'yaml json 转换 配置 kubernetes docker-compose',
    about: '适合在 Kubernetes 清单、docker-compose、CI 配置之间转换;支持 YAML 锚点引用与 --- 多文档。',
    component: lazy(() => import('./yaml-json/YamlJson.vue')),
  },
  {
    id: 'cron-explainer', name: 'Cron 表达式解读', category: 'dev', icon: 'clock',
    desc: '把 Cron 表达式翻译成中文人话,附字段速查表',
    keywords: 'cron crontab 表达式 定时任务 计划任务 解读',
    about: '输入 5 段式 Cron 表达式(分 时 日 月 周),立即给出中文描述;写定时任务配置时用来确认含义再合适不过。工具参数会同步到地址栏,点标题栏「分享状态」或直接复制链接即可分享当前配置。',
    component: lazy(() => import('./cron-explainer/CronExplainer.vue')),
  },
  {
    id: 'cron-builder', name: 'Cron 表达式生成器', category: 'dev', icon: 'hourglass',
    desc: '可视化拼 Cron 表达式,实时中文含义与未来 5 次执行时间',
    keywords: 'cron 生成器 定时任务 计划任务 crontab 下次执行 调度',
    about: '与「Cron 表达式解读」配套:8 组常用预设一键填入,五个字段分开编辑并实时校验,即时给出中文含义与接下来 5 次执行时间(按本机时区逐分钟推算,日与周同时受限按标准「或」语义)。表达式会同步到地址栏,复制链接即可分享。',
    component: lazy(() => import('./cron-builder/CronBuilder.vue')),
  },
  {
    id: 'user-agent', name: 'UA 解析', category: 'dev', icon: 'scan-face',
    desc: '解析 User-Agent 得到浏览器、系统、设备与引擎信息',
    keywords: 'user agent ua 解析 浏览器 设备 系统 ua-parser',
    about: '粘贴任意 UA 字符串(默认为本机浏览器),解析出浏览器/版本、操作系统、设备类型与渲染引擎,用于日志分析与兼容性排查。',
    component: lazy(() => import('./user-agent/UserAgentParser.vue')),
  },
  {
    id: 'http-status', name: 'HTTP 状态码速查', category: 'dev', icon: 'traffic-cone',
    desc: '常见 HTTP 状态码的含义、场景与中文解释',
    keywords: 'http 状态码 404 500 301 接口 速查',
    about: '按 1xx~5xx 分色显示,支持按码值或关键字搜索;点击码值即可复制。',
    component: lazy(() => import('./http-status/HttpStatusCodes.vue')),
  },
  {
    id: 'subnet-calc', name: 'IPv4 子网计算器', category: 'dev', icon: 'network',
    desc: 'CIDR / 掩码换算网络地址、广播地址与可用主机范围',
    keywords: '子网 cidr 掩码 ip 网段 广播地址 主机数 运维 网络',
    about: '输入 192.168.1.100/24 或 10.0.0.0 255.255.0.0 均可,自动计算网络/广播地址、可用主机区间与数量,并识别私有地址段(10/172.16/192.168/127/169.254/100.64)。非连续掩码会被拒绝。工具参数会同步到地址栏,点标题栏「分享状态」或直接复制链接即可分享当前配置。',
    component: lazy(() => import('./subnet-calc/SubnetCalc.vue')),
  },
  {
    id: 'chmod', name: 'Chmod 计算', category: 'dev', icon: 'key-round',
    desc: '可视化勾选权限位,得到 755 等八进制与符号式',
    keywords: 'chmod 权限 linux 755 644 setuid 文件',
    about: '勾选 rwx 与特殊位(setuid / setgid / sticky),实时得到八进制与符号式表示;也可以直接输入 755 反推勾选。附带可复制的 chmod 命令。',
    component: lazy(() => import('./chmod/ChmodCalculator.vue')),
  },
  {
    id: 'aes-crypto', name: 'AES 文本加解密', category: 'dev', icon: 'lock-keyhole',
    desc: '基于密码的 AES-256-GCM 文本加解密,密文可分享',
    keywords: 'aes 加密 解密 gcm pbkdf2 密码 安全',
    about: '使用浏览器原生 Web Crypto:PBKDF2-SHA256(12 万次迭代)从密码派生密钥,AES-256-GCM 加密。密文包含随机 salt 与 iv,同一密码每次加密结果都不同;忘记密码无法找回。',
    component: lazy(() => import('./aes-crypto/AesCrypto.vue')),
  },
  {
    id: 'file-hash', name: '文件哈希校验', category: 'dev', icon: 'file-check',
    desc: '计算文件的 MD5 / SHA 系列哈希,校验下载完整性',
    keywords: '文件 哈希 md5 sha256 校验 下载 完整性 checksum',
    about: '拖入任意文件计算 MD5 与 SHA-1/256/384/512。MD5 分块增量计算,SHA 由 Web Crypto 完成;与官方提供的校验值比对即可确认文件未被篡改。',
    component: lazy(() => import('./file-hash/FileHash.vue')),
  },
  {
    id: 'keycode', name: '按键检测', category: 'dev', icon: 'keyboard',
    desc: '按下任意键显示 event.key / code / keyCode 与修饰键状态',
    keywords: 'keycode 按键 键盘 key code 修饰键 快捷键 调试 javascript',
    about: '按下键盘上任意一个键,实时显示 event.key、event.code(物理键位)与旧的 keyCode,以及 Ctrl/Alt/Shift/Meta/CapsLock 状态,可一键复制 JSON,适合写快捷键逻辑或排查键盘映射时参考。工具只监听不拦截,不影响你的任何组合键;keyCode 已被标准废弃,仅供兼容旧代码时查用。',
    component: lazy(() => import('./keycode/KeycodeInfo.vue')),
  },

  // ---------- 文本工具 ----------
  {
    id: 'markdown', name: 'Markdown 预览', category: 'text', icon: 'file-code',
    desc: '实时渲染 Markdown,所见即所得的排版预览',
    keywords: 'markdown md 预览 渲染 编辑器',
    about: '左侧编辑右侧实时预览,输出经过 DOMPurify 消毒,可一键复制渲染后的 HTML 用于邮件或网页。',
    component: lazy(() => import('./markdown/MarkdownPreview.vue')),
  },
  {
    id: 'md-toc', name: 'Markdown 目录生成', category: 'text', icon: 'table-of-contents',
    desc: '提取标题生成带锚点链接的目录,跳过代码块',
    keywords: 'markdown 目录 toc 锚点 标题 readme 文档 博客 生成',
    about: '从 Markdown 提取 H1–H6 标题,生成 GitHub 风格锚点链接的目录(小写化、剔标点、空格转 -、连续连字符不合并,与 GitHub 渲染结果一致),代码块内的 # 行不会误判。层级范围与有序/无序列表可调,复制后直接贴进 README 或博客顶部。选项会同步到地址栏,点标题栏「分享状态」或直接复制链接即可分享当前配置。',
    component: lazy(() => import('./md-toc/MdToc.vue')),
  },
  {
    id: 'regex', name: '正则测试', category: 'text', icon: 'regex',
    desc: '在线测试正则表达式,高亮匹配结果并展示分组',
    keywords: 'regex 正则 表达式 测试 匹配 regexp',
    about: '支持 g/i/m/s/u 标志,实时高亮全部匹配并展示捕获分组;检测到嵌套量词等灾难性回溯模式时会给出警告。匹配数上限 500 处。工具参数会同步到地址栏,点标题栏「分享状态」或直接复制链接即可分享当前配置。',
    component: lazy(() => import('./regex/RegexTester.vue')),
  },
  {
    id: 'text-stats', name: '文本统计', category: 'text', icon: 'chart-column',
    desc: '统计字符、词数、行数、UTF-8 字节数与阅读时长',
    keywords: '字数统计 字符 行数 字节 word count 文本',
    about: '中英文混排分别统计:汉字按字计数,英文按单词计数;字节数按 UTF-8 编码计算,写作投稿时很有用。',
    component: lazy(() => import('./text-stats/TextStats.vue')),
  },
  {
    id: 'word-frequency', name: '词频统计', category: 'text', icon: 'trending-up',
    desc: '统计英文单词与中文字符的出现频率,支持 Top N',
    keywords: '词频 字频 统计 frequency 单词 出现次数',
    about: '英文按单词(含连字符与撇号)统计并小写归一;中文按单字统计。按频率降序展示占比条形图。',
    component: lazy(() => import('./word-frequency/WordFrequency.vue')),
  },
  {
    id: 'text-diff', name: '文本比对', category: 'text', icon: 'git-compare-arrows',
    desc: '逐行对比两段文本差异,高亮新增与删除的行',
    keywords: '文本比对 diff 对比 差异 比较',
    about: '基于 LCS(最长公共子序列)算法的行级 diff,绿色为新增、红色为删除;支持导出标准 diff 格式。单次对比上限 2000 行。',
    component: lazy(() => import('./text-diff/TextDiff.vue')),
  },
  {
    id: 'text-replace', name: '文本替换', category: 'text', icon: 'replace',
    desc: '批量查找替换文本,支持正则表达式与忽略大小写',
    keywords: '文本替换 查找 替换 replace 正则',
    about: '默认按字面量替换($ 符号不会被解释);勾选正则后可用 $1、$2 引用捕获分组,例如把 2026-09-30 换成 09/30/2026。',
    component: lazy(() => import('./text-replace/TextReplace.vue')),
  },
  {
    id: 'text-extract', name: '文本提取', category: 'text', icon: 'magnet',
    desc: '从文本中提取 URL、邮箱、数字、手机号、IP 地址',
    keywords: '提取 url 邮箱 数字 手机号 ip 文本',
    about: '五种常用模式一键提取,自动去重;手机号按中国大陆号段识别,IP 会校验每段不超过 255。',
    component: lazy(() => import('./text-extract/TextExtract.vue')),
  },
  {
    id: 'text-clean', name: '文本清理', category: 'text', icon: 'paintbrush',
    desc: '删除空行、重复行、空格、首尾空白,合并连续空白',
    keywords: '删除空行 删除重复行 删除空格 清理 文本',
    about: '七个清理操作基于输入文本生成输出,输出框可直接编辑,方便继续微调;实时显示前后字符数。',
    component: lazy(() => import('./text-clean/TextClean.vue')),
  },
  {
    id: 'pangu', name: '中文排版格式化', category: 'text', icon: 'text-quote',
    desc: '中英文之间加空格、全半角标点归一,一键整理排版',
    keywords: '盘古之白 中英文 空格 排版 格式化 全角 半角 标点 文案 公众号',
    about: '俗称「盘古之白」:在中文与英文/数字之间加空格,是技术文档与公众号排版的主流惯例。附带全角字母数字转半角、中文后半角标点转全角(不碰 3.5 这类小数点)、合并连续空格与行尾空白五项开关,可叠加使用。正文不会写入地址栏,分享链接只携带排版选项。',
    component: lazy(() => import('./pangu/PanguFormat.vue')),
  },
  {
    id: 'sort-lines', name: '文本行整理', category: 'text', icon: 'arrow-down-wide-narrow',
    desc: '多行文本排序、去重、反转、随机打乱、加行号,一键整理',
    keywords: '排序 去重 行 排列 随机 打乱 行号 名单 清单 文本 sort shuffle',
    about: '四种排序:字母序(本地化规则、忽略大小写)、数字序(按行首数字数值排,2 排在 10 前面)、按长度与随机打乱(加密级随机,适合抽签);另附去重、去空行、行首尾去空白与加行号(可补零)。操作按顺序叠加,结果可直接覆盖原文继续处理。正文不会写入地址栏,分享链接只携带整理选项。',
    component: lazy(() => import('./sort-lines/SortLines.vue')),
  },
  {
    id: 'case-convert', name: '大小写转换', category: 'text', icon: 'case-sensitive',
    desc: '全大写、全小写、标题大写、大小写互换、驼峰/下划线',
    keywords: '大小写 大写 小写 标题 驼峰 snake camel 转换',
    about: '除基本大小写外,支持 camelCase / PascalCase / snake_case / kebab-case 互转,写代码变量名时非常顺手。',
    component: lazy(() => import('./case-convert/CaseConvert.vue')),
  },
  {
    id: 'text-reverse', name: '文本反转', category: 'text', icon: 'undo-2',
    desc: '将整段文本或每一行文字顺序反转',
    keywords: '文本反转 倒序 反转 reverse 文字',
    about: '按字形簇(grapheme)反转,组合字符与 👨‍👩‍👧 这类 ZWJ emoji 不会被拆散。',
    component: lazy(() => import('./text-reverse/TextReverse.vue')),
  },
  {
    id: 'whitespace-convert', name: '空格换行转换', category: 'text', icon: 'arrow-down-up',
    desc: '换行与空格、Tab 与空格互相转换',
    keywords: '换行转空格 空格转回车 tab 空格 空白 转换',
    about: '五种常见空白转换:处理从 PDF/Excel 复制出来的文本、缩进风格调整时很好用。',
    component: lazy(() => import('./whitespace-convert/WhitespaceConvert.vue')),
  },
  {
    id: 'invisible-chars', name: '换行符与零宽字符', category: 'text', icon: 'eraser',
    desc: '统计统一 CRLF/LF,揪出并清除零宽字符等隐形捣乱者',
    keywords: '换行符 crlf lf 零宽字符 隐形字符 bom 空白 清理 不可见 排查',
    about: '排查「字符串看起来一样却比不相等」的元凶:统计 CRLF 与 LF 数量并一键统一;逐类揪出零宽空格、BOM 等零宽字符并一键清除;「显示不可见字符」模式把空格、Tab、NBSP 等渲染成可见占位符。清理直接替换原文,可继续编辑。',
    component: lazy(() => import('./invisible-chars/InvisibleChars.vue')),
  },
  {
    id: 'morse', name: '摩尔斯电码', category: 'text', icon: 'radio',
    desc: '文本与摩尔斯电码互转,支持字母数字与常用标点',
    keywords: '摩尔斯 摩斯 电码 morse 编码 解码',
    about: '字母间用空格分隔、单词间用 / 分隔;无法识别的字符会以 # 或 ? 标出。',
    component: lazy(() => import('./morse/MorseCode.vue')),
  },
  {
    id: 'text-split', name: '文本分割', category: 'text', icon: 'scissors',
    desc: '按分隔符或固定长度把文本拆分成列表',
    keywords: '文本分割 分隔符 拆分 切分 分段',
    about: '支持自定义分隔符(逗号/空格/竖线/换行)或按固定字符数切分;可复制为纯列表、带序号列表或 JSON 数组。',
    component: lazy(() => import('./text-split/TextSplit.vue')),
  },

  // ---------- 图片工具 ----------
  {
    id: 'image-compress', name: '图片压缩', category: 'image', icon: 'shrink',
    desc: '批量本地压缩图片,可调质量与尺寸,支持 JPG / WebP / PNG',
    keywords: '图片压缩 压缩 批量 image compress webp 缩放 图片 zip',
    about: '批量压缩:一次拖入最多 30 张,统一调质量、输出格式与最大宽度,逐张显示压缩前后体积与节省比例,支持单张下载或打包 ZIP。通过 Canvas 重编码实现,JPEG 输出自动铺白底避免透明区域变黑。',
    component: lazy(() => import('./image-compress/ImageCompress.vue')),
  },
  {
    id: 'image-base64', name: '图片转 Base64', category: 'image', icon: 'file-image',
    desc: '将图片编码为 Data URL,生成 img / CSS 代码片段',
    keywords: '图片 base64 dataurl 编码 内联 图片',
    about: '输出 Data URL、<img> 标签与 CSS background 三种片段;建议只内联小图标,超过 100KB 的图片会显著增大页面体积。',
    component: lazy(() => import('./image-base64/ImageToBase64.vue')),
  },
  {
    id: 'image-corner', name: '图片圆角', category: 'image', icon: 'square-dashed',
    desc: '给图片添加圆角,透明背景输出 PNG',
    keywords: '图片 圆角 圆形 rounded corner 图片处理',
    about: '圆角程度 100% 即为正圆,适合做头像;输出透明背景 PNG,可叠加在任何背景上。',
    component: lazy(() => import('./image-corner/ImageCorner.vue')),
  },
  {
    id: 'image-rotate', name: '图片旋转翻转', category: 'image', icon: 'rotate-cw',
    desc: '图片旋转 90° / 180°,水平或垂直镜像翻转',
    keywords: '图片 旋转 翻转 镜像 rotate flip 图片调整',
    about: '旋转与镜像可以叠加操作(如先右转 90° 再水平镜像),随时可重置回原图。',
    component: lazy(() => import('./image-rotate/ImageRotate.vue')),
  },
  {
    id: 'image-border', name: '图片加边框', category: 'image', icon: 'frame',
    desc: '为图片添加纯色边框与留白,自定义颜色粗细',
    keywords: '图片 边框 留白 border 图片处理 相框',
    about: '边框紧贴图片,留白在边框之外;「留白区域透明」选项可输出带透明外边的 PNG。',
    component: lazy(() => import('./image-border/ImageBorder.vue')),
  },
  {
    id: 'image-filter', name: '图片滤镜调色', category: 'image', icon: 'sliders-horizontal',
    desc: '灰度、反色、复古、毛玻璃、马赛克、油画、铅笔画等滤镜',
    keywords: '图片 滤镜 调色 灰度 复古 毛玻璃 马赛克 像素化 油画 铅笔画 照片',
    about: '常规滤镜基于 Canvas filter;马赛克按强度调整像素块大小,油画是色彩量化算法、铅笔画是灰度反色模糊 + color dodge 混合,全部本地像素运算,大图处理约需一秒。',
    component: lazy(() => import('./image-filter/ImageFilter.vue')),
  },
  {
    id: 'color-picker', name: '颜色吸取器', category: 'image', icon: 'pipette',
    desc: '上传图片点击取色,或用屏幕吸管吸取任意颜色',
    keywords: '取色 颜色吸取 吸管 color picker 色值 调色',
    about: '在图片上点击吸取颜色并积累成色板;「屏幕吸管」(Chrome/Edge)可吸取屏幕上任意位置的颜色,做设计还原很方便。',
    component: lazy(() => import('./color-picker/ColorPickerTool.vue')),
  },
  {
    id: 'palette-extract', name: '图片取色调色板', category: 'image', icon: 'paint-bucket',
    desc: '提取图片主色形成调色板,显示占比,可导出 CSS 变量',
    keywords: '取色 主色 调色板 配色 palette 图片 分析 配色方案',
    about: '上传图片后按 RGB 量化分桶统计主色,给出前 N 个主色的 HEX 与像素占比(数量可调 1~12),点击色块复制,或一键导出为 CSS 变量。做设计配色、提取品牌色时很顺手;统计完全在本地进行。与「颜色吸取器」互补:那边精确取一个像素,这边看整张图的主色构成。',
    component: lazy(() => import('./palette-extract/PaletteExtract.vue')),
  },
  {
    id: 'image-crop', name: '图片裁切', category: 'image', icon: 'crop',
    desc: '按 1:1、4:3、16:9 等比例裁切图片,可选裁切位置',
    keywords: '图片 裁切 裁剪 crop 比例 头像',
    about: '选择目标比例后按比例内切原图,九宫格按钮决定窗口位置,滑块控制窗口大小;导出即裁切结果。',
    component: lazy(() => import('./image-crop/ImageCrop.vue')),
  },
  {
    id: 'image-merge', name: '图片拼接', category: 'image', icon: 'combine',
    desc: '多张图片纵向或横向拼接成长图,可设间距背景',
    keywords: '图片拼接 长图 合并 合成 拼图 stitch',
    about: '按列表顺序拼接,可调间距、四周留白与背景色;拼接结果超过 16384px 时会提示(浏览器画布上限)。',
    component: lazy(() => import('./image-merge/ImageMerge.vue')),
  },
  {
    id: 'image-format', name: '图片格式转换', category: 'image', icon: 'refresh-cw',
    desc: 'PNG / JPG / WebP 互转,显示转换前后体积对比',
    keywords: '图片 格式转换 png jpg webp 互转',
    about: '转换前后的体积一目了然;转 JPG 时自动铺白底(该格式无透明通道)。WebP 通常体积最小。',
    component: lazy(() => import('./image-format/ImageFormat.vue')),
  },
  {
    id: 'image-watermark', name: '图片加水印', category: 'image', icon: 'droplet',
    desc: '文字或 Logo 水印,支持平铺防盗图与九宫格位置',
    keywords: '图片 水印 文字 logo 平铺 防盗 版权',
    about: '文字水印可调字号/颜色/透明度/旋转,「平铺全图」模式是防盗图的标准做法;也可上传 Logo 图片作为水印,位置用九宫格选定。',
    component: lazy(() => import('./image-watermark/ImageWatermark.vue')),
  },
  {
    id: 'image-grid', name: '九宫格切图', category: 'image', icon: 'grid-3x3',
    desc: '切成 3×3 九张图,按发布顺序编号打包 ZIP',
    keywords: '九宫格 切图 朋友圈 微信 微博 拼图 3x3',
    about: '默认先居中裁成正方形再等分(微信/微博九宫格的标准做法),按发布顺序 1-9 编号,下载 ZIP 后按顺序上传即可。',
    component: lazy(() => import('./image-grid/ImageGrid.vue')),
  },
  {
    id: 'id-photo', name: '证件照换背景', category: 'image', icon: 'contact',
    desc: '自动识别纯色背景并替换为白/蓝/红/自定义色',
    keywords: '证件照 换背景 一寸 报名照 蓝底 白底 红底',
    about: '自动从图片边缘取样背景色,按容差替换为目标色,过渡带做边缘羽化。适合背景均匀的证件照;容差越小边缘越干净但残留越多,可自行调节。',
    component: lazy(() => import('./id-photo/IdPhoto.vue')),
  },
  {
    id: 'image-exif', name: '图片信息/EXIF', category: 'image', icon: 'info',
    desc: '查看拍摄参数与 GPS 位置,分享原图前先检查',
    keywords: 'exif 信息 相机 参数 gps 位置 隐私 查看',
    about: '读取相机品牌型号、拍摄时间、曝光/光圈/ISO/焦距等参数与 GPS 坐标(附地图链接)。⚠️ 反向提醒:分享原图会泄露位置,发图前建议抹除。',
    component: lazy(() => import('./image-exif/ImageExif.vue')),
  },
  {
    id: 'favicon', name: 'favicon 生成器', category: 'image', icon: 'component',
    desc: '一张图生成全尺寸 favicon.ico 与 PNG',
    keywords: 'favicon ico 图标 网站 生成 站点图标 多尺寸',
    about: '上传一张图(建议 ≥256×256 正方形),自动居中裁切生成 16/32/48/64/128/256 六个尺寸,打包成标准 .ico(内嵌 PNG,全浏览器兼容)下载,单个尺寸的 PNG 也可单独下载。文件名可用站点标识自定义。工具参数会同步到地址栏,点标题栏「分享状态」或直接复制链接即可分享当前配置。',
    component: lazy(() => import('./favicon/FaviconMaker.vue')),
  },

  // ---------- 生成器 ----------
  {
    id: 'uuid', name: 'UUID / NanoID / ULID', category: 'generate', icon: 'id-card',
    desc: '批量生成 UUID v4、NanoID 短 ID 与可排序 ULID',
    keywords: 'uuid guid ulid nanoid 短id 生成 唯一标识 随机 主键',
    about: '三种 ID 一页生成:UUID v4 由加密级随机数生成,122 位随机空间碰撞可忽略,可大写/去连字符;NanoID 是 21 字符左右的 URL 安全短 ID(长度 6~64 可调),适合做主键与分享码;ULID 为 26 位大写 Crockford Base32,前 10 位是毫秒时间戳、可按字典序排序也可反解时间。全部使用浏览器加密级随机数,无第三方依赖。',
    component: lazy(() => import('./uuid/UuidGenerator.vue')),
  },
  {
    id: 'password', name: '密码生成', category: 'generate', icon: 'key',
    desc: '生成高强度随机密码,自定义长度与字符集',
    keywords: '密码 随机 生成 password 安全',
    about: '使用加密级随机数与拒绝采样(无取模偏差);强度按信息熵估算。可排除 i l 1 L o 0 O 等易混淆字符。',
    component: lazy(() => import('./password/PasswordGenerator.vue')),
  },
  {
    id: 'qrcode', name: '二维码生成', category: 'generate', icon: 'qr-code',
    desc: '将文本或链接生成二维码,可加中央 Logo,自定义尺寸与颜色',
    keywords: '二维码 qr code 生成 扫码 logo 美化',
    about: '输入内容变化后自动重新生成;可自定义前景/背景色,导出 PNG。支持上传中央 Logo(自动切换 H 级纠错保证遮挡后仍可扫描,大小可调)。长文本会自动使用更密集的版本。工具参数会同步到地址栏,点标题栏「分享状态」或直接复制链接即可分享当前配置。',
    component: lazy(() => import('./qrcode/QrCodeTool.vue')),
  },
  {
    id: 'url-qr', name: '网址转二维码', category: 'generate', icon: 'external-link',
    desc: '输入网址生成二维码,扫码直达网页,自动补全 https',
    keywords: '网址 url 链接 二维码 扫码 网页 打开',
    about: '专用于网页链接:漏写 https:// 会自动补全,生成后可一键复制链接或下载 PNG,扫码即在手机上打开网页。工具参数会同步到地址栏,点标题栏「分享状态」或直接复制链接即可分享当前配置。',
    component: lazy(() => import('./url-qr/UrlQr.vue')),
  },
  {
    id: 'wifi-qr', name: 'WiFi 转二维码', category: 'generate', icon: 'wifi',
    desc: '扫码免密码连接 Wi-Fi,支持 WPA/WEP 与隐藏网络',
    keywords: 'wifi 二维码 wi-fi 无线 扫码连接 密码 访客',
    about: '按 Wi-Fi 二维码标准格式(WIFI:T:…;S:…;P:…;)生成,iPhone 与安卓相机扫码后直接连入网络;密码中的特殊字符自动转义。适合打印贴在办公室/店铺。',
    component: lazy(() => import('./wifi-qr/WifiQr.vue')),
  },
  {
    id: 'qr-decode', name: '二维码解析', category: 'generate', icon: 'scan-qr-code',
    desc: '上传或粘贴二维码图片,本地识别出其中的内容',
    keywords: '二维码解析 识别 decode qr 扫码 读码',
    about: '支持拖拽与 Ctrl+V 粘贴截图;超大图会先等比缩小再识别。识别全程本地完成。',
    component: lazy(() => import('./qr-decode/QrDecode.vue')),
  },
  {
    id: 'barcode', name: '条形码生成', category: 'generate', icon: 'barcode',
    desc: '生成 CODE128 / EAN-13 / UPC 等标准条形码',
    keywords: '条形码 barcode code128 ean upc 生成',
    about: '每种码制对内容格式有要求(如 EAN-13 需要 12/13 位数字),不符合时会给出提示;导出白色背景 PNG 可直接印刷。',
    component: lazy(() => import('./barcode/BarcodeTool.vue')),
  },
  {
    id: 'random-number', name: '随机数生成', category: 'generate', icon: 'dice-5',
    desc: '生成范围内的随机整数,支持批量、去重、排序',
    keywords: '随机数 random 抽签 抽奖 数字',
    about: '使用 crypto.getRandomValues 与拒绝采样,分布均匀无偏差;范围跨度上限约 43 亿。',
    component: lazy(() => import('./random-number/RandomNumber.vue')),
  },
  {
    id: 'number-to-english', name: '数字↔英文', category: 'generate', icon: 'languages',
    desc: '数字与英文读法双向转换,支持负数与小数',
    keywords: '数字 英文 number english 转换 单词',
    about: '数字转英文支持到千万亿级;反向解析支持逗号分隔写法(如 two thousand, twenty-six)与小数(point 读法)。',
    component: lazy(() => import('./number-to-english/NumberToEnglish.vue')),
  },
  {
    id: 'mock-data', name: '随机测试数据', category: 'generate', icon: 'flask-conical',
    desc: '批量生成姓名、手机号、身份证等测试数据',
    keywords: '测试数据 mock 假数据 姓名 手机号 身份证 填充',
    about: '一键生成表格数据,身份证号校验位合法但纯属随机,仅供开发测试填充;可复制为 CSV 或 JSON。',
    component: lazy(() => import('./mock-data/MockData.vue')),
  },
  {
    id: 'lorem', name: '假文生成器', category: 'generate', icon: 'pilcrow',
    desc: '生成 Lorem Ipsum 占位假文,按段落或句子,可输出 HTML',
    keywords: 'lorem ipsum 假文 乱数 占位 排版 设计 mockup 哑文',
    about: '生成排版行业沿用了五百多年的 Lorem Ipsum 占位假文,按段落或句子控制数量,可选以经典的「Lorem ipsum dolor sit amet」开头、用 <p> 标签包裹输出。词库内置在页面里,生成完全离线,每批随机。工具参数会同步到地址栏,点标题栏「分享状态」或直接复制链接即可分享当前配置。',
    component: lazy(() => import('./lorem/LoremGenerator.vue')),
  },
  {
    id: 'gif-maker', name: 'GIF 合成', category: 'generate', icon: 'image-play',
    desc: '多图合成动图/表情包,逐帧调延迟',
    keywords: 'gif 动图 表情包 合成 帧 动画 制作',
    about: '多张图片按顺序合成一张 GIF:每帧可独立调节停留时长(50~1500ms)、上下移动排序,输出尺寸可选,支持透明背景(适合做表情包)。合成完全在本地进行。与摩尔斯电码、随机测试数据同属「生成器」分类。',
    component: lazy(() => import('./gif-maker/GifMaker.vue')),
  },

  // ---------- 计算换算 ----------
  {
    id: 'timestamp', name: '时间戳转换', category: 'calc', icon: 'calendar-clock',
    desc: 'Unix 时间戳与日期时间互转,支持秒 / 毫秒',
    keywords: '时间戳 timestamp unix 日期 转换',
    about: '输入 10 位自动按秒、13 位按毫秒处理;双向实时联动,顶部常驻当前时间戳。工具参数会同步到地址栏,点标题栏「分享状态」或直接复制链接即可分享当前配置。',
    component: lazy(() => import('./timestamp/TimestampTool.vue')),
  },
  {
    id: 'color', name: '颜色转换', category: 'calc', icon: 'palette',
    desc: 'HEX / RGB / HSL 颜色格式互转,实时预览色块',
    keywords: '颜色 color hex rgb hsl 转换 调色 色值',
    about: '支持 3/6/8 位 HEX(#rrggbbaa)、rgba() 与 hsla();带透明度时 HEX 输出 8 位、HSL 采用现代斜杠语法。工具参数会同步到地址栏,点标题栏「分享状态」或直接复制链接即可分享当前配置。',
    component: lazy(() => import('./color/ColorConverter.vue')),
  },
  {
    id: 'unit', name: '单位换算', category: 'calc', icon: 'ruler',
    desc: '长度、重量、温度、面积、体积、压力等 17 大类换算',
    keywords: '单位换算 长度 重量 温度 面积 体积 压力 能量 换算',
    about: '17 类单位:长度、重量、温度、数据、速度、面积、体积、时间、角度、压力、能量、功率、频率、电流、电压、光照度、配速。温度与配速(和速度互为倒数)按专用公式换算。',
    component: lazy(() => import('./unit/UnitConverter.vue')),
  },
  {
    id: 'roman', name: '罗马数字互转', category: 'calc', icon: 'landmark',
    desc: '阿拉伯数字与罗马数字互相转换(1 ~ 3999)',
    keywords: '罗马数字 roman 数字 转换',
    about: '支持 1~3999 的标准罗马数字;反向解析会校验书写格式合法性(如 IIII 会被拒绝)。',
    component: lazy(() => import('./roman/RomanConverter.vue')),
  },
  {
    id: 'date-calc', name: '日期计算器', category: 'calc', icon: 'calendar-days',
    desc: '日期差、加减天数与工作日推算',
    keywords: '日期 计算 天数 工作日 日期差 加减 推算 倒计时',
    about: '两个日期之间隔多少天/多少个工作日,或从一个日期推算 N 天(N 个工作日)后是哪天。工作日按跳过周六/周日计算;法定节假日与调休每年由国务院发布,本工具不包含,请自行核对。',
    component: lazy(() => import('./date-calc/DateCalc.vue')),
  },
  {
    id: 'rmb-uppercase', name: '人民币大写', category: 'calc', icon: 'banknote',
    desc: '数字金额转中文大写,报销单/合同直接可用',
    keywords: '人民币 大写 金额 中文 财务 报销 发票 数字大写',
    about: '按财务规范转换:拾位必须写「壹拾」、角后无分写「整」、零档补零。支持千分位逗号,精确到分,上限 9999 亿。工具参数会同步到地址栏,点标题栏「分享状态」或直接复制链接即可分享当前配置。',
    component: lazy(() => import('./rmb-uppercase/RmbUppercase.vue')),
  },
  {
    id: 'contrast', name: '颜色对比度检查', category: 'calc', icon: 'contrast',
    desc: 'WCAG 对比度计算,AA/AAA 达标一眼判定',
    keywords: '对比度 wcag aa aaa 无障碍 颜色 可读性 contrast 设计',
    about: '按 WCAG 2.1 公式计算文字与背景的对比度(1 ~ 21),并判定普通文字与大文字的 AA / AAA 等级(阈值 4.5 / 7 / 3 / 4.5),附实时预览,适合检查界面配色是否满足无障碍要求。工具参数会同步到地址栏,点标题栏「分享状态」或直接复制链接即可分享当前配置。',
    component: lazy(() => import('./contrast/ContrastChecker.vue')),
  },
  {
    id: 'tz-convert', name: '时区会议换算', category: 'calc', icon: 'earth',
    desc: '同一时刻在 18 个时区的本地时间,挑开会时间不头疼',
    keywords: '时区 换算 会议 时间 国际 utc gmt 夏令时',
    about: '选一个基准时间与时区,一眼看到北京/东京/伦敦/纽约/悉尼等 18 个时区对应的本地日期与时间,标注 UTC 偏移、相对基准的时差与「是否工作时间」(当地 9:00~18:00),夏令时由系统 Intl 自动处理。工具参数会同步到地址栏,点标题栏「分享状态」或直接复制链接即可分享当前配置。',
    component: lazy(() => import('./tz-convert/TzConvert.vue')),
  },
  {
    id: 'lunar-calendar', name: '农历公历互转', category: 'calc', icon: 'moon',
    desc: '公历查农历(干支生肖)与农历反查公历,1900–2100',
    keywords: '农历 阴历 公历 互转 干支 生肖 春节 老黄历 日期 lunar',
    about: '公历日期一键查农历(含闰月标注、干支纪年与生肖),农历(年/月/日/闰月)反查公历日期;覆盖 1900–2100 年,数据表以历年春节锚点与全年逐日往返校验。注意干支按农历年取,与按立春排盘的工具有差异。日期会同步到地址栏,点标题栏「分享状态」或直接复制链接即可分享当前配置。',
    component: lazy(() => import('./lunar-calendar/LunarCalendar.vue')),
  },
  {
    id: 'mortgage', name: '房贷计算器', category: 'calc', icon: 'piggy-bank',
    desc: '等额本息 / 等额本金月供与总利息对比,支持商贷+公积金组合',
    keywords: '房贷 月供 等额本息 等额本金 利息 公积金 组合贷款 贷款 计算器 买房',
    about: '商业贷款与公积金贷款可以分别填金额、利率与期限,两笔按月合并成一份月供;等额本息(月供固定)与等额本金(月供递减)两种方式都算一遍,直观对比总利息差与首月压力差。附按年还款明细与提前还款测算:第 N 期后一次性还一笔,同时给出「期限不变减月供」与「月供不变缩期限」两种走法各自的剩余利息与节省金额。计算完全在本地进行,利率请以实际审批为准。工具参数会同步到地址栏,点标题栏「分享状态」或直接复制链接即可分享当前配置。',
    component: lazy(() => import('./mortgage/MortgageCalc.vue')),
  },
  {
    id: 'color-shades', name: '色阶生成器', category: 'calc', icon: 'swatch-book',
    desc: '一个主色生成 50~950 完整色阶,导出 Tailwind / CSS 变量',
    keywords: '色阶 调色板 配色 颜色 tailwind css 变量 设计 主色 shades',
    about: '以输入色为 500 档基准(明度钳制在 30%–62%),按固定明度锚点向两端推亮/推暗,生成 Tailwind 风格的 50~950 共 11 档色阶,色相保持不变;每个色块按亮度自动选择黑/白文字并标注该底色下的 WCAG 对比度,点击即复制 HEX。支持一键导出 Tailwind 配置与 CSS 变量,变量名可自定义。工具参数会同步到地址栏,点标题栏「分享状态」或直接复制链接即可分享当前配置。',
    component: lazy(() => import('./color-shades/ColorShades.vue')),
  },
  {
    id: 'rate-convert', name: '利率换算', category: 'calc', icon: 'percent',
    desc: '日 / 月 / 年利率互转,单利复利两种口径,看清「日息万几」的真实年化',
    keywords: '利率 换算 年化 日息 万几 月息 单利 复利 apr 贷款 借钱',
    about: '在日 / 月 / 年利率之间换算,支持单利与复利两种口径;内置「万1 / 万5 / 千1 / 月息1分」快捷输入并自动切换档位,显示对应的口头表述。贷款广告只说「日息万几」时,换算成年化利率才能看清真实成本(如日息万 5 单利即年化 18.25%)。计算在本地完成,工具参数会同步到地址栏,点标题栏「分享状态」或直接复制链接即可分享当前配置。',
    component: lazy(() => import('./rate-convert/RateConvert.vue')),
  },

  // ---------- 文档处理 ----------
  {
    id: 'pdf-merge', name: 'PDF 合并', category: 'doc', icon: 'files',
    desc: '将多个 PDF 按顺序合并为一个文件',
    keywords: 'pdf 合并 merge 拼接 文档',
    about: '按列表顺序合并,可上下移动调整;加密 PDF 会被明确拒绝而不是产出损坏文件。全部处理在浏览器完成,PDF 不上传。',
    component: lazy(() => import('./pdf-merge/PdfMerge.vue')),
  },
  {
    id: 'pdf-organize', name: 'PDF 页面整理', category: 'doc', icon: 'rows-3',
    desc: '按页码提取、删除、旋转页面,或逐页拆分为 ZIP',
    keywords: 'pdf 拆分 提取 删除 旋转 页码 split extract 重排',
    about: '页码范围写法如 1-3,5,8-9。「按此页序重排」允许任意顺序与重复页(如 3,1-2,3);逐页拆分会打包成 ZIP。',
    component: lazy(() => import('./pdf-organize/PdfOrganize.vue')),
  },
  {
    id: 'pdf-watermark', name: 'PDF 添加水印', category: 'doc', icon: 'stamp',
    desc: '为 PDF 每一页添加倾斜的半透明文字水印',
    keywords: 'pdf 水印 watermark 文字 版权',
    about: '每页居中绘制倾斜的半透明水印,可调字号、透明度与角度。注意:PDF 标准字体不支持中文,请使用英文/数字水印。',
    component: lazy(() => import('./pdf-watermark/PdfWatermark.vue')),
  },
  {
    id: 'pdf-page-number', name: 'PDF 添加页码', category: 'doc', icon: 'list-ordered',
    desc: '在 PDF 页面底部添加「第 x 页 / 共 y 页」页码',
    keywords: 'pdf 页码 页数 添加 页脚',
    about: '三个位置可选(左下/居中/右下),支持自定义起始页码与是否显示总页数,适合打印装订前补页码。',
    component: lazy(() => import('./pdf-page-number/PdfPageNumber.vue')),
  },
  {
    id: 'image-to-pdf', name: '图片转 PDF', category: 'doc', icon: 'printer',
    desc: '多张图片合并转换为一个 PDF 文件,每图一页',
    keywords: '图片 pdf 转换 jpg png 合并',
    about: '每张图片一页、页面尺寸与图片一致;WebP 等格式会先转成 JPEG 再嵌入(透明区域铺白底)。',
    component: lazy(() => import('./image-to-pdf/ImageToPdf.vue')),
  },
  {
    id: 'excel-convert', name: 'Excel 格式转换', category: 'doc', icon: 'sheet',
    desc: 'Excel / CSV 转 JSON、CSV、Markdown、HTML、TXT',
    keywords: 'excel csv json markdown html txt 表格 转换 xlsx',
    about: 'CSV 自动识别 UTF-8 与 GBK 编码(中文 Excel 导出不乱码);多工作表会全部转换并以标题分隔。',
    component: lazy(() => import('./excel-convert/ExcelConvert.vue')),
  },
  {
    id: 'json-excel', name: 'JSON ↔ Excel', category: 'doc', icon: 'table',
    desc: 'JSON 数组生成 Excel / CSV 文件,Excel 也可转回 JSON',
    keywords: 'json excel 互转 xlsx csv 表格 json转excel excel转json',
    about: '正向要求 JSON 对象数组(键即表头);CSV 导出带 BOM,Excel 双击打开不乱码。反向支持多 Sheet(输出按 Sheet 名分组)。',
    component: lazy(() => import('./json-excel/JsonExcel.vue')),
  },
  {
    id: 'excel-merge', name: 'Excel 合并/拆分', category: 'doc', icon: 'library',
    desc: '多个 Excel 合并为一个多 Sheet 文件,或反向拆分',
    keywords: 'excel 合并 拆分 sheet 工作表 xlsx 多文件',
    about: '合并时所有工作表汇入一个 xlsx(同名自动加序号);拆分把每个 Sheet 导出为独立 xlsx 并打包 ZIP。',
    component: lazy(() => import('./excel-merge/ExcelMerge.vue')),
  },
  {
    id: 'xlsx-sql', name: 'Excel → SQL', category: 'doc', icon: 'database-zap',
    desc: '把 Excel / CSV 行生成 INSERT INTO 语句,MySQL / PG 方言',
    keywords: 'excel csv sql insert 生成 数据库 灌数据 导入 mysql postgresql',
    about: '选一个 Excel / CSV,把每行数据生成 INSERT INTO 语句用于给测试库灌数据:MySQL(反引号)与 PostgreSQL(双引号)两种方言、多行合并或每行一条、空单元格输出 NULL、字符串自动转义单引号、日期按 YYYY-MM-DD HH:MM:SS;多工作表可切换,结果可复制或下载 .sql。全部在本地解析,不上传文件。',
    component: lazy(() => import('./xlsx-sql/XlsxSql.vue')),
  },

  // ---------- 文档转换 ----------
  {
    id: 'pdf-to-image', name: 'PDF 转图片', category: 'dconv', icon: 'images',
    desc: '每一页渲染为高清 PNG / JPG,打包 ZIP 下载',
    keywords: 'pdf 转图片 转png 转jpg 渲染 截图 页面',
    about: '基于 pdf.js 逐页渲染:1x 标清适合屏幕浏览,2x/3x 高清适合印刷;支持 PNG 与 JPG 两种格式,多页自动打包 ZIP。',
    component: lazy(() => import('./pdf-to-image/PdfToImage.vue')),
  },
  {
    id: 'pdf-extract', name: 'PDF 提取文本', category: 'dconv', icon: 'scan-text',
    desc: '提取 PDF 全部文字,导出为 纯文本 / Word / HTML',
    keywords: 'pdf 提取文本 转word 转html 转txt 文字',
    about: '按页提取全部文字,可复制或导出为 .txt / .docx / .html,HTML 版还支持直接打印存为 PDF。⚠️ 仅提取文字层,不含图片与原始排版(浏览器无法做到高保真版式还原)。',
    component: lazy(() => import('./pdf-extract/PdfExtract.vue')),
  },
  {
    id: 'pdf-compress', name: 'PDF 压缩', category: 'dconv', icon: 'archive',
    desc: '重采样页面压缩 PDF 体积,可调清晰度与质量',
    keywords: 'pdf 压缩 缩小 体积 减小 光栅化',
    about: '原理:把每页渲染成 JPEG 后重新组装为 PDF,倍率与质量越低体积越小;⚠️ 压缩后文字变为图片,不可选中/搜索。若压缩结果比原文件还大(纯文字 PDF),会明确提示。',
    component: lazy(() => import('./pdf-compress/PdfCompress.vue')),
  },
  {
    id: 'word-to-html', name: 'Word 转 HTML', category: 'dconv', icon: 'file-type',
    desc: '解析 .docx 为 HTML 预览,可复制 / 下载 / 打印存 PDF',
    keywords: 'word docx 转 html 转pdf 预览 mammoth',
    about: '基于 mammoth 解析 .docx,保留标题、段落、列表、表格与图片;支持复制 HTML、下载网页文件,以及「打印 / 存为 PDF」(走浏览器打印)。⚠️ 仅支持 .docx,旧版二进制 .doc 无法在浏览器解析。',
    component: lazy(() => import('./word-to-html/WordToHtml.vue')),
  },
  {
    id: 'excel-export', name: 'Excel 转图片/PDF', category: 'dconv', icon: 'image-down',
    desc: '把表格渲染成 PNG 长图或 A4 分页 PDF',
    keywords: 'excel 转图片 转pdf 表格 截图 长图 分页',
    about: '本地把表格数据绘制成带表头与斑马纹的表格图:PNG(多工作表打包 ZIP)或 A4 纵向 PDF(长表自动分页)。',
    component: lazy(() => import('./excel-export/ExcelExport.vue')),
  },
  {
    id: 'format-convert', name: '办公格式互转', category: 'dconv', icon: 'arrow-left-right',
    desc: 'XLSX ↔ XLS ↔ ODS ↔ CSV ↔ HTML 互转',
    keywords: 'xlsx xls ods csv 转换 格式互转 openoffice wps',
    about: '基于 SheetJS 的全格式互转:现代 Excel、Excel 97-2003、OpenDocument(ODS)、CSV 与 HTML 网页表格之间任意转换,多工作表完整保留(CSV 仅导出首个)。',
    component: lazy(() => import('./format-convert/FormatConvert.vue')),
  },

  // ---------- 音视频 ----------
  {
    id: 'tts', name: '文字转语音', category: 'av', icon: 'mic',
    desc: '使用系统语音朗读文本,可调音色、语速与音调',
    keywords: '文字转语音 tts 朗读 语音合成 配音 播报',
    about: '调用操作系统内置的语音合成引擎(Web Speech API),音色数量取决于系统语言包;朗读在本地进行,不上传文本。',
    component: lazy(() => import('./tts/TtsTool.vue')),
  },
  {
    id: 'video-frame', name: '视频截帧', category: 'av', icon: 'camera',
    desc: '播放本地视频并截取任意画面为图片',
    keywords: '视频 截帧 截图 视频截图 帧 frame',
    about: '支持跳转到指定秒数精确截帧,截取的帧以原始分辨率导出 PNG;视频文件不离开本机。',
    component: lazy(() => import('./video-frame/VideoFrame.vue')),
  },
  {
    id: 'audio-edit', name: '音频剪辑', category: 'av', icon: 'sliders-vertical',
    desc: '波形预览,裁剪片段、倒放、调整音量,导出 WAV',
    keywords: '音频 剪切 裁剪 倒放 音量 wav 波形',
    about: '解码后显示波形图,拖动起点/终点选择区间,支持倒放与 0~300% 音量,导出 16bit PCM WAV。试听使用共享 AudioContext,可反复操作。',
    component: lazy(() => import('./audio-edit/AudioEdit.vue')),
  },
  {
    id: 'screen-record', name: '在线录屏', category: 'av', icon: 'monitor-play',
    desc: '录制屏幕 / 窗口 / 标签页,导出 WebM 视频',
    keywords: '录屏 屏幕录制 录像 录课 record webm',
    about: '开始后由浏览器弹出共享选择器(屏幕/窗口/标签页),支持暂停与麦克风混录;录制内容只保存在本地。需要 https 或 localhost 环境。',
    component: lazy(() => import('./screen-record/ScreenRecord.vue')),
  },
  {
    id: 'cam-mic-test', name: '摄像头麦克风测试', category: 'av', icon: 'webcam',
    desc: '开会前试一试摄像头与麦克风:画面、分辨率、帧率与收音电平',
    keywords: '摄像头 麦克风 测试 会议 视频通话 相机 摄像头检测 麦克风检测 webcam',
    about: '一键开启摄像头与麦克风,本地预览画面并显示实际分辨率 / 帧率,麦克风电平表实时反映收音是否正常,同时列出检测到的全部设备;任何画面与声音都不会被录制或上传。权限被拒、设备被占用等失败情形都有明确的中文提示。需要 https 或 localhost 环境。',
    component: lazy(() => import('./cam-mic-test/CamMicTest.vue')),
  },

  // ---------- 数据图表 ----------
  {
    id: 'chart', name: '图表制作', category: 'chart', icon: 'chart-line',
    desc: '粘贴数据一键生成柱状、折线、饼图、雷达等 10 种图表',
    keywords: '图表 柱状图 折线图 饼图 雷达图 散点图 漏斗图 图表制作',
    about: '数据格式:每行一条,逗号分隔,第一列是标签、其余列是数值;首行若为非数字则视为系列名。基于 ECharts 按需打包,可导出 2x 高清 PNG。',
    component: lazy(() => import('./chart/ChartTool.vue')),
  },

  // ---------- 办公辅助 ----------
  {
    id: 'pomodoro', name: '番茄钟', category: 'office', icon: 'timer',
    desc: '专注工作 25 分钟,休息 5 分钟,可自定义时长',
    keywords: '番茄钟 番茄工作法 专注 计时器 pomodoro',
    about: '基于真实时钟倒计时(后台标签页被浏览器节流也不影响准确性),阶段结束自动衔接并播放提示音。',
    component: lazy(() => import('./pomodoro/Pomodoro.vue')),
  },
  {
    id: 'stopwatch', name: '秒表与倒计时', category: 'office', icon: 'alarm-clock',
    desc: '精确到百分秒的秒表(可计次)与倒计时,后台走时也准确',
    keywords: '秒表 停表 计时 倒计时 计次 stopwatch timer 提醒',
    about: '秒表精确到百分秒,支持计次并自动标出最快 / 最慢一圈,计次记录可一键复制 CSV;快捷键:空格开始/暂停、L 计次、R 重置;倒计时时分秒任意组合,附常用预设,结束播放提示音。计时基于系统时间戳而非累计间隔,把页面切到后台或电脑休眠后恢复,结果依然准确。',
    component: lazy(() => import('./stopwatch/Stopwatch.vue')),
  },
  {
    id: 'decision', name: '小决定', category: 'office', icon: 'compass',
    desc: '选择困难症救星:是/否决定,或从选项中随机挑选',
    keywords: '小决定 随机 决定 抽签 选择 yes no',
    about: '两种模式:Yes/No 快速拍板,或多行选项随机抽取(带滚动动画)。',
    component: lazy(() => import('./decision/DecisionTool.vue')),
  },
  {
    id: 'drawing-pad', name: '在线画板', category: 'office', icon: 'pen-tool',
    desc: '简单好用的手绘画板,支持画笔、橡皮、撤销与导出',
    keywords: '画板 绘画 涂鸦 白板 drawing sketch 画图',
    about: '支持鼠标与触屏手写,8 种常用色、20 步撤销;导出为 1000×620 白底 PNG。',
    component: lazy(() => import('./drawing-pad/DrawingPad.vue')),
  },
  {
    id: 'zip', name: 'ZIP 压缩/解压', category: 'office', icon: 'package',
    desc: '多文件打包为 ZIP,或解压 ZIP 提取其中文件',
    keywords: 'zip 压缩 解压 打包 提取 文件',
    about: '基于 fflate 在浏览器本地完成;解压有单文件 200MB 的安全上限(防压缩炸弹),文本文件可直接预览。',
    component: lazy(() => import('./zip/ZipTool.vue')),
  },
  {
    id: 'gradient', name: 'CSS 渐变生成', category: 'office', icon: 'aperture',
    desc: '可视化调配线性 / 径向渐变,一键复制 CSS 代码',
    keywords: '渐变 gradient css 配色 背景 设计',
    about: '支持线性/径向、任意角度与三色停靠点,内置六组精选配色;复制生成的 CSS 可直接使用。',
    component: lazy(() => import('./gradient/GradientGenerator.vue')),
  },

  // ---------- 软件推荐 ----------
  {
    id: 'software-recommend', name: '系统必备软件推荐', category: 'software', icon: 'app-window',
    desc: '人工精选的装机必备清单:系统 / 开发 / 办公 / 影音 / 安全 / 备份等 14 类',
    keywords: '软件推荐 装机必备 必备软件 精选 清单 下载 系统',
    about: '145 款长期使用与社区口碑验证的软件,按 14 大用途分类(系统/开发/办公/影音/下载/远程/安全/备份/输入法/浏览器扩展/邮件通讯/虚拟机/文件传输/磁盘恢复),标注免费与开源属性、适用人群并直达官网。杀毒软件覆盖国内外主流产品并如实标注特点;清单为人工维护的静态数据(非自动抓取),与所列软件无任何推广合作;下载请认准官网,谨防捆绑。',
    component: lazy(() => import('./software-recommend/SoftwareRecommend.vue')),
  },
]

export function getTool(id) {
  return TOOLS.find((t) => t.id === id)
}
